### ISSUE TITLE
When I use the MobileNetV2 Quantized model, the model cannot be loaded.

### ISSUE THREAD

**Issue by yeyupiaoling** [bwasti/AICamera#66]
I download and use this model: https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized#model

cannot load this  model, error logs:
```
11-06 16:41:09.713 10644-10644/? I/art: Late-enabling -Xcheck:jni
11-06 16:41:09.731 10644-10644/? W/ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
        at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
        at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
        at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
        at android.os.Looper.prepareMainLooper(Looper.java:112)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
11-06 16:41:09.772 10644-10644/facebook.f8demo I/art: Starting a blocking GC AddRemoveAppImageSpace
11-06 16:41:09.862 10644-10644/facebook.f8demo I/InstantRun: starting instant run server: is main process
11-06 16:41:10.049 10644-10644/facebook.f8demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-06 16:41:10.065 10644-10665/facebook.f8demo E/F8DEMO: Attempting to load protobuf netdefs...
11-06 16:41:10.076 10644-10664/facebook.f8demo W/System: ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
11-06 16:41:10.080 10644-10644/facebook.f8demo D/AccessibilityManager: current package=facebook.f8demo, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
11-06 16:41:10.120 10644-10665/facebook.f8demo E/F8DEMO: done.
    Instantiating predictor...
11-06 16:41:10.126 10644-10665/facebook.f8demo E/native: [E operator.cc:105] Cannot find operator schema for Int8GivenIntTensorFill. Will skip schema checking.
11-06 16:41:10.201 10644-10667/facebook.f8demo I/Adreno: QUALCOMM build                   : 4f3d4bc, I07a8b16b27
    Build Date                       : 10/26/17
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : mybranch28842968
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
11-06 16:41:10.210 10644-10667/facebook.f8demo I/OpenGLRenderer: Initialized EGL, version 1.4
11-06 16:41:10.210 10644-10667/facebook.f8demo D/OpenGLRenderer: Swap behavior 1
11-06 16:41:10.221 10644-10644/facebook.f8demo I/CameraManagerGlobal: Connecting to camera service
11-06 16:41:10.224 10644-10657/facebook.f8demo I/FeatureParser: can't find capricorn.xml in assets/device_features/,it may be in /system/etc/device_features
```

What should I do? Thanks.

**Comment by dvlee1024** [comment]
@yeyupiaoling hi，did you solve this problem？

**Comment by yeyupiaoling** [comment]
@dvlee1024 Maybe. I don't think this model can be used in this project.

**Comment by ndinhtuan** [comment]
@yeyupiaoling  Sorry, Can you tell me a little bit about solution (maybe using different method) ?
