### ISSUE TITLE
Camera permissions problem on Android-M

### ISSUE THREAD

**Issue by victorv** [bwasti/AICamera#7]
This is normally solved by building with pre-M SDK.

>19 19:23:28.288 377-1273/? W/ServiceManager: Permission failure: android.permission.CAMERA from uid=10167 pid=26536
04-19 19:23:28.288 377-1273/? E/CameraService: Permission Denial: can't use the camera pid=26536, uid=10167
04-19 19:23:28.288 26536-26536/com.example.bwasti.aicamera W/CameraBase: An error occurred while connecting to camera: 0
04-19 19:23:28.289 26536-26536/com.example.bwasti.aicamera D/AndroidRuntime: Shutting down VM
   
>com.example.bwasti.aicamera E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.bwasti.aicamera, PID: 10972
                                                                             java.lang.RuntimeException: Unable to resume activity {com.example.bwasti.aicamera/com.example.bwasti.aicamera.MainActivity}: java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3124)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3155)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
                                                                                 at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5459)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                              Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.<init>(Camera.java:511)
                                                                                 at android.hardware.Camera.open(Camera.java:368)
                                                                                 at com.example.bwasti.aicamera.MainActivity.onResume(MainActivity.java:78)

**Comment by Jia-HongHenryLee** [comment]
@victorv  Solution: Open the phone’s Settings > Apps > AI Camera > Permissions and enable Camera

**Comment by victorv** [comment]
@Jia-HongHenryLee - thanks. Yes - that works.

Also changing app/build.gradle to 
        minSdkVersion 21
        targetSdkVersion 21

**Comment by bwasti** [comment]
overhauled the app completely and this issue should no longer exist (I've added a permissions check)
